version: 2
updates:
  - package-ecosystem: "npm" # or other package managers like "bundler", "pip", etc.
    directory: "/" # location where the package manager's configuration file is located
    schedule:
      interval: "weekly" # or "weekly", "monthly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
